# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

- name: Ensure telnet server and client are not installed (CIS)
  become: true
  ansible.builtin.package:
    name:
      - 'telnet'
      - 'telnet-server'
    state: absent
