# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/telnet
  block:

    - name: CIS | Ensure telnet server and client are not installed
      become: true
      ansible.builtin.package:
        name:
          - 'telnet'
          - 'telnetd'
          - 'telnet-server'
          - 'telnet-ssl'
          - 'telnetd-ssl'
        state: absent

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_telnet'
